site_name: StarFinder Citizen
site_url: http://starfindercitizen.space/
nav:
    - Home: index.md
    - Overview: overview.md
    - 'Character Creation': 'charactercreation.md'
    - Races: 
      - Human: races/human.md
      - "Xi'an": races/xian.md
      - Banu: races/banu.md
      - Tevarin: races/tevarin.md 
      - Vanduul: races/vanduul.md
    - Classes: 
      - Envoy: classes/envoy.md
      - Engineer: classes/engineer.md
      - Operative: classes/operative.md
      - Scientist: classes/scientist.md
      - Soldier : classes/soldier.md
      - Worker: classes/worker.md
    - Skills: skills.md
    - Feats: feats.md
    - Equipment: 
      - Equipment: equipment/equipment.md
      - Weapons: equipment/weapons.md
      - Armor: equipment/armor.md
      - Augmentations: equipment/augmentations.md
      - Computers: equipment/computer.md
      - 'Technological Items': equipment/techitems.md
      - Vehicles: equipment/vehicles.md
      - 'Other Purchases': equipment/other.md
    - 'Tactical Rules': tacticalrules.md
    - Starships: starships.md
    - 'Game Mastering': game-mastering.md
    - 'Setting and Lore': settinglore.md
theme: windmill-dark